#!/bin/sh

set -euo pipefail
# Initialization - load function handler
# The function handler is of the format [handler-file-name-without-extn].[handler-method]

# Get the file name
lambda_script_name="$(echo $_HANDLER | cut -d. -f1)"
handler="$(echo $_HANDLER | cut -d. -f2-)"
echo $handler

# The /opt location is read-only, so to modify the bootstrap file
# we need to copy it to tmp that is writable
mkdir -p /tmp/dart
cp /opt/dart/bootstrap.dart /tmp/dart/bootstrap.dart

# Layers are extracted to the /opt directory in the function execution environment.
# Replace the import directive with the actual path to the dart file
sed -i "s|{{LAMBDA_HANDLER_PATH}}|${LAMBDA_TASK_ROOT}/${lambda_script_name}.dart|" /tmp/dart/bootstrap.dart

# Execute the bootstrap dart function with the handler data
/opt/dart/bin/dart /tmp/dart/bootstrap.dart "$handler"